# Generated by Django 4.2.6 on 2023-10-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trades",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_type", models.CharField(max_length=5)),
                ("currency", models.CharField(max_length=5)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("timestamp", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="UserPortfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=24)),
                ("cryptocurrency", models.CharField(max_length=5)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="date_of_birth",
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.CharField(default="NULL", max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="rank",
            field=models.CharField(default="7th Kyu", max_length=64),
            preserve_default=False,
        ),
    ]
